#!/bin/bash

refresh() {
  local url="$1"
  local dir="$2"

  if [ -d $dir ]; then
    cd $dir && git pull && cd ..
  else
    git clone $url $dir --depth=1
  fi
}

refresh git://github.com/gregsexton/gitv.git                    gitv
refresh git://github.com/bronson/vim-trailing-whitespace.git    vim-trailing-whitespace
refresh git://github.com/ervandew/supertab.git                  supertab
refresh git://github.com/vim-scripts/php.vim--Nicholson.git     php.vim-nicholson
refresh git://github.com/vim-scripts/php.vim--Garvin.git        php.vim-garvin

refresh git://github.com/tpope/vim-cucumber.git                 vim-cucumber
refresh git://github.com/tpope/vim-git.git                      vim-git
refresh git://github.com/tpope/vim-fugitive.git                 vim-fugitive
refresh git://github.com/tpope/vim-pathogen.git                 vim-pathogen
refresh git://github.com/tpope/vim-ragtag.git                   vim-ragtag
refresh git://github.com/tpope/vim-repeat.git                   vim-repeat
refresh git://github.com/tpope/vim-surround.git                 vim-surround
refresh git://github.com/tpope/vim-haml.git                     vim-haml
refresh git://github.com/tpope/vim-rails.git                    vim-rails

refresh git://github.com/scrooloose/nerdtree.git                nerdtree
refresh git://github.com/beyondwords/vim-twig.git               vim-twig
refresh git://github.com/cakebaker/scss-syntax.vim.git          scss-syntax
refresh git://github.com/kchmck/vim-coffee-script.git           vim-coffee-script
refresh git://github.com/intuited/lh-vim-lib.git                lh-vim-lib
refresh git://github.com/ervandew/relative.git                  relative
refresh git://github.com/timcharper/textile.vim.git             textile
refresh git://github.com/vim-scripts/PDV-revised.git            phpdoc
refresh git://github.com/int3/vim-extradite.git                 vim-extradite
refresh git://github.com/vim-ruby/vim-ruby.git                  vim-ruby
refresh git://github.com/tobiassvn/vim-gemfile.git              vim-gemfile
refresh git://github.com/claco/jasmine.vim.git                  jasmine.vim
refresh git://github.com/othree/html5.vim.git                   html5.vim
refresh git://github.com/hail2u/vim-css3-syntax.git             css3-syntax
